# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: eryudi-m <eryudi-m@student.42sp.org.br>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/02/20 03:39:22 by eryudi-m          #+#    #+#              #
#    Updated: 2023/02/20 03:41:06 by eryudi-m         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

#Settings to have unity test ready
#http://www.throwtheswitch.org/build/make
#https://github.com/ThrowTheSwitch/Unity


build_test:
	git clone https://github.com/ThrowTheSwitch/Unity.git ../unity
	git pull
	mkdir ../src/
	
